export const types = {
  //login
  GET_GOOGLE_IDENTITY: "GET_GOOGLE_IDENTITY",
  LOGIN: "LOGIN",
  TWO_FACTOR_VALIDATE: "TWO_FACTOR_VALIDATE",
  CHECK_LOGIN_FINISH: "CHECK_LOGIN_FINISH",
  LOGOUT: "LOGOUT",
  //Modal
  UI_OPEN_MODAL: "UI_OPEN_MODAL",
  UI_CLOSE_MODAL: "UI_CLOSE_MODAL",
  //inventories
  INVENTORY_LOADED: "LOAD_INVENTORY",
  INVENTORY_COUNT: "INVENTORY_COUNT",
  ADD_NEW_INVENTORY: "ADD_NEW_INVENTORY",
  ADD_INVENTORY_SUCCESS: "ADD_INVENTORY_SUCCESS",
  ADD_INVENTORY_ERROR: "ADD_INVENTORY_ERROR",
  INVENTORY_SET_ACTIVE: "INVENTORY_SET_ACTIVE",
  INVENTORY_CLEAR_ACTIVE: "INVENTORY_CLEAR_ACTIVE",
  INVENTORY_UPDATED: "INVENTORY_UPDATE",
  INVENTORY_UPDATE_ERROR: "INVENTORY_UPDATE_ERROR",
  INVENTORY_DELETED: "INVENTORY_DELETED",
  INVENTORY_LOGOUT: "INVENTORY_LOGOUT",
  INVENTORY_IMAGE_UPLOADED: "INVENTORY_IMAGE_UPLOADED",
  INVENTORY_IMAGE_UPLOAD_ERROR: "INVENTORY_IMAGE_UPLOAD_ERROR",

  //Aparts
  APART_LOADED: "APART_LOADED",
  ADD_NEW_APART: "ADD_NEW_APART",
  ADD_APART_SUCCESS: "ADD_APART_SUCCESS",
  ADD_APART_ERROR: "ADD_APART_ERROR",
  APART_SET_ACTIVE: "APART_SET_ACTIVE",
  APART_CLEAR_ACTIVE: "APART_CLEAR_ACTIVE",
  APART_DELETE: "APART_DELETE",
  APART_DELETE_SUCCESS: "APART_DELETE_SUCCESS",
  APART_DELETE_ERROR: "APART_DELETE_ERROR",

  //Records
  RECORDS_LOADED: "RECORDS_LOADED",
};
