export const types = {

  GET_GOOGLE_IDENTITY:'GET_GOOGLE_IDENTITY',
  LOGIN: 'LOGIN',
  TWO_FACTOR_VALIDATE: 'TWO_FACTOR_VALIDATE',
  CHECK_LOGIN_FINISH: "CHECK_LOGIN_FINISH",
  LOGOUT: "LOGOUT",

};
