export const types = {
  //login
  GET_GOOGLE_IDENTITY: "GET_GOOGLE_IDENTITY",
  LOGIN: "LOGIN",
  TWO_FACTOR_VALIDATE: "TWO_FACTOR_VALIDATE",
  CHECK_LOGIN_FINISH: "CHECK_LOGIN_FINISH",
  LOGOUT: "LOGOUT",
  //Modal
  UI_OPEN_MODAL: "UI_OPEN_MODAL",
  UI_CLOSE_MODAL: "UI_CLOSE_MODAL",
  //inventories
  ADD_NEW_INVENTORY: "ADD_NEW_INVENTORY",
  ADD_INVENTORY_SUCCESS: "ADD_INVENTORY_SUCCESS",
  ADD_INVENTORY_ERROR: "ADD_INVENTORY_ERROR",
  LOAD_INVENTORY: "LOAD_INVENTORY",
};
